### ISSUE TITLE
能主动发送消息吗？

### ISSUE THREAD

**Issue by yuyang0** [open-dingtalk/dingtalk-stream-sdk-go#12]
就是在没有收到消息的情况下主动发送消息

**Comment by Zeymo** [comment]
> 就是在没有收到消息的情况下主动发送消息

stream本身是双工的通道，当前开放的场景只能基于钉钉测触发。主动发消息暂时还是要通过钉钉开放平台的发消息接口

**Comment by yuyang0** [comment]
@Zeymo 发消息要个userId，真不知道机器人从哪里拿这个userId
