### ISSUE TITLE
大家有没有出现reconnect后无法收到第一条消息的情况？

### ISSUE THREAD

**Issue by zhengyangs** [open-dingtalk/dingtalk-stream-sdk-go#16]
企业内部应用，go-stream sdk 0.8版本，接收机器人消息，程序运行初期消息接收及响应正常。但出现自动reconnect并成功后，无法接收到发送给机器人的第一条消息，第二条及后续消息正常接收。
reconnect前提示如下信息：[ERROR] connection process read message error: messageType=[-1] message=[] error=[websocket: close 1006 (abnormal closure): unexpected EOF]

**Comment by chzealot** [comment]
这个问题目前没有复现，方便的话，可以在我们的交流群里提供 ClientID，让技术支持人员协助解决：https://opensource.dingtalk.com/developerpedia/docs/explore/support?via=moon-group
