### ISSUE TITLE
大哥来看看

### ISSUE THREAD

**Issue by hutao01-miku** [open-dingtalk/dingtalk-stream-sdk-go#17]
这个机器人目前能发送图片信息或者语音，视频吗？从服务器发送，而不是markdown渲染公网链接

**Comment by chzealot** [comment]
可以的，官网有上传图片、视频文件的API，调用API上传后就可以发送对应的多媒体消息

例如：
https://opensource.dingtalk.com/developerpedia/docs/learn/stream/faq#3-markdown-%E4%B8%AD%E6%8F%92%E5%85%A5%E7%9A%84%E5%9B%BE%E7%89%87%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E9%97%AE%E9%A2%98

**Comment by hutao01-miku** [comment]
> 可以的，官网有上传图片、视频文件的API，调用API上传后就可以发送对应的多媒体消息
> 
> 例如： https://opensource.dingtalk.com/developerpedia/docs/learn/stream/faq#3-markdown-%E4%B8%AD%E6%8F%92%E5%85%A5%E7%9A%84%E5%9B%BE%E7%89%87%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E9%97%AE%E9%A2%98

谢谢，这个上传确实方便，意思就是我想让机器人发什么消息，先把消息发给这个接口，生成一个唯一的media_id，再让机器人发出来这个media_id给用户,就可以实现机器人发送各种消息了，应该是这样吧

**Comment by chzealot** [comment]
> > 可以的，官网有上传图片、视频文件的API，调用API上传后就可以发送对应的多媒体消息
> > 例如： https://opensource.dingtalk.com/developerpedia/docs/learn/stream/faq#3-markdown-%E4%B8%AD%E6%8F%92%E5%85%A5%E7%9A%84%E5%9B%BE%E7%89%87%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E9%97%AE%E9%A2%98
> 
> 谢谢，这个上传确实方便，意思就是我想让机器人发什么消息，先把消息发给这个接口，生成一个唯一的media_id，再让机器人发出来这个media_id给用户,就可以实现机器人发送各种消息了，应该是这样吧

是的，先通过 API 上传文件，再发送消息。目前发送消息对文件类型支持可能还不够完整，更多类型不支持的场景，可以随时反馈给我们，我们会持续完善。
